apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "rwmany"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  # storageClassName: